version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "@stylistic/*"
          - "eslint-plugin-*"
      karma:
        patterns:
          - "karma"
          - "karma-*"
          - "qunit"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
